---
- name: Enable Nginx Channel (amzn2)
  become: true
  shell: amazon-linux-extras enable {{ nginx_amazon_extras_channel }}
  changed_when: false
  when: ansible_distribution == 'Amazon' and nginx_amazon_extras_enabled | bool
  tags: [ nginx ]

- name: Add Nginx Repository (rhel)
  become: true
  copy:
    content: |
      [nginx]
      name=Nginx Repository
      baseurl=http://nginx.org/packages/rhel/{{ rhel_distribution_major_version }}/$basearch/
      gpgcheck=0
      enabled=1
    dest: /etc/yum.repos.d/nginx.repo
    mode: '0644'
  when: ansible_distribution != 'Amazon' or not nginx_amazon_extras_enabled | bool
  tags: [ nginx ]

- name: Install Nginx
  become: true
  yum:
    name: nginx
    update_cache: true
    state: present
  tags: [ nginx ]
